using BackEndPets.Application.Interfaces;
using BackEndPets.Domain.Entities;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BackEndPets.Infrastructure.Services;

public sealed class QuestPdfClinicalDocumentGenerationService(Cloudinary? cloudinary)
    : IPetClinicalDocumentGenerationService
{
    public async Task<string> GenerateAsync(
        Pet pet,
        PetClinicalRecord record,
        IReadOnlyCollection<PetClinicalEvent> events,
        string ownerFullName,
        string? ownerPhone,
        string? ownerAddress,
        string? ownerEmail)
    {
        if (cloudinary is null)
            throw new InvalidOperationException("Cloudinary is not configured; cannot store the generated PDF.");

        var orderedEvents = events.OrderBy(e => e.EventDate).ToList();

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.DefaultTextStyle(x => x.FontSize(10));

                page.Header().Column(col =>
                {
                    col.Item().Text("Balto — Official Clinical History").FontSize(18).Bold();
                    col.Item().Text($"Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC").FontSize(8).FontColor(Colors.Grey.Medium);
                });

                page.Content().Column(col =>
                {
                    col.Spacing(12);

                    col.Item().Element(c => SectionTitle(c, "Pet details"));
                    col.Item().Text($"Name: {pet.Name}    Species: {pet.Species ?? "N/A"}    Breed: {pet.Breed ?? "N/A"}");
                    col.Item().Text($"Sex: {pet.Sex ?? "N/A"}    Color: {pet.Color ?? "N/A"}    Weight: {pet.Weight?.ToString("0.##") ?? "N/A"} kg");
                    col.Item().Text($"Born: {pet.BirthDate?.ToString("yyyy-MM-dd") ?? "N/A"}    ID number: {pet.IdentificationNumber ?? "N/A"}    Microchip: {pet.MicrochipNumber ?? "N/A"}");

                    col.Item().Element(c => SectionTitle(c, "Owner details"));
                    col.Item().Text($"Name: {ownerFullName}    Phone: {ownerPhone ?? "N/A"}");
                    col.Item().Text($"Address: {ownerAddress ?? "N/A"}    Email: {ownerEmail ?? "N/A"}");

                    col.Item().Element(c => SectionTitle(c, "Medical summary"));
                    col.Item().Text($"Allergies: {record.Allergies ?? "None recorded"}");
                    col.Item().Text($"Chronic conditions: {record.ChronicConditions ?? "None recorded"}");
                    col.Item().Text($"Dietary restrictions: {record.DietaryRestrictions ?? "None recorded"}");

                    col.Item().Element(c => SectionTitle(c, "Vaccines"));
                    AppendEventList(col, orderedEvents.Where(e => e.EventType == PetClinicalEventType.Vaccine));

                    col.Item().Element(c => SectionTitle(c, "Surgeries"));
                    AppendEventList(col, orderedEvents.Where(e => e.EventType == PetClinicalEventType.Surgery));

                    col.Item().Element(c => SectionTitle(c, "Medications"));
                    foreach (var med in orderedEvents.SelectMany(e => e.Medications))
                        col.Item().Text($"• {med.Name} — {med.Dose ?? "N/A"}, {med.Frequency ?? "N/A"}, {med.Duration ?? "N/A"}");

                    col.Item().Element(c => SectionTitle(c, "Clinical event timeline"));
                    foreach (var e in orderedEvents)
                    {
                        col.Item().Text($"{e.EventDate:yyyy-MM-dd} — {e.EventType.ToUpperInvariant()} — {e.Reason ?? e.Diagnosis ?? "No reason recorded"}").Bold();
                        if (!string.IsNullOrWhiteSpace(e.Diagnosis)) col.Item().Text($"   Diagnosis: {e.Diagnosis}");
                        if (!string.IsNullOrWhiteSpace(e.ExamResults)) col.Item().Text($"   Results: {e.ExamResults}");
                        if (!string.IsNullOrWhiteSpace(e.Recommendations)) col.Item().Text($"   Recommendations: {e.Recommendations}");
                        if (!string.IsNullOrWhiteSpace(e.Observations)) col.Item().Text($"   Observations: {e.Observations}");
                        if (e.NextControlDate is not null) col.Item().Text($"   Next check-up: {e.NextControlDate:yyyy-MM-dd}");
                    }

                    col.Item().Element(c => SectionTitle(c, "Last updated"));
                    col.Item().Text($"{record.UpdatedAt:yyyy-MM-dd HH:mm} UTC");
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Document automatically generated by Balto from structured information. ");
                    t.Span("It does not replace a licensed veterinarian's judgment.").FontColor(Colors.Grey.Medium);
                });
            });
        });

        using var stream = new MemoryStream();
        document.GeneratePdf(stream);
        stream.Position = 0;

        var uploadParams = new RawUploadParams
        {
            File = new FileDescription($"clinical-history-{pet.Id}.pdf", stream),
            Folder = "balto/clinical-history",
            UseFilename = true,
            UniqueFilename = true,
            Overwrite = false
        };

        var result = await cloudinary.UploadAsync(uploadParams);
        return result.SecureUrl.ToString();
    }

    private static void SectionTitle(QuestPDF.Infrastructure.IContainer container, string title) =>
        container.Text(title).FontSize(13).Bold().FontColor(Colors.Blue.Darken2);

    private static void AppendEventList(QuestPDF.Fluent.ColumnDescriptor col, IEnumerable<PetClinicalEvent> events)
    {
        var list = events.ToList();
        if (list.Count == 0)
        {
            col.Item().Text("None recorded.").FontColor(Colors.Grey.Medium);
            return;
        }
        foreach (var e in list)
            col.Item().Text($"• {e.EventDate:yyyy-MM-dd} — {e.Reason ?? e.Diagnosis ?? "No detail"}");
    }
}
