version: "3.9"

services:
  api:
    image: back-end-pets:production
    container_name: back-end-pets-production
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Jwt__Key=${JWT_KEY}
      - Ai__VetDocumentProvider=${AI_PROVIDER}
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - Gemini__Model=${GEMINI_MODEL}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
      - OpenAI__Model=${OPENAI_MODEL}
      - OpenRouter__ApiKey=${OPENROUTER_API_KEY}
      - OpenRouter__Model=${OPENROUTER_MODEL}
    networks:
      - proxy

networks:
  proxy:
    external: true