version: "3.9"

services:
  api:
    image: back-end-pets:production
    container_name: back-end-pets-production
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION}
      - Jwt__Key=${JWT_KEY}
    networks:
      - proxy

networks:
  proxy:
    external: true