<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>BackEndPets.API</RootNamespace>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>9f98e0a4-8ed3-48f1-8ea8-805e45d67ade</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.5" />
        <PackageReference Include="CloudinaryDotNet" Version="1.27.5" />
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\BackEndPets.Application\BackEndPets.Application.csproj" />
      <ProjectReference Include="..\BackEndPets.Infrastructure\BackEndPets.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="obj\Debug\net10.0\" />
    </ItemGroup>

</Project>
